# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Hapi < Formula
  desc "Hostinger API CLI"
  homepage "https://www.hostinger.com"
  version "1.2.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/hostinger/api-cli/releases/download/v1.2.0/hapi-1.2.0-darwin-amd64.tar.gz"
      sha256 "8f2931d70af63d2f5e149a6a2c1e4fe07dc16949edf43fb5920df178a391596a"

      define_method(:install) do
        bin.install "hapi"
        bash_completion.install "completions/hapi.bash" => "hapi"
        zsh_completion.install  "completions/hapi.zsh"  => "_hapi"
        fish_completion.install "completions/hapi.fish"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/hostinger/api-cli/releases/download/v1.2.0/hapi-1.2.0-darwin-arm64.tar.gz"
      sha256 "5cb95d02268bc67b56fb815c7cc5b410189e0797b2a77ea3c8e3d101823366c6"

      define_method(:install) do
        bin.install "hapi"
        bash_completion.install "completions/hapi.bash" => "hapi"
        zsh_completion.install  "completions/hapi.zsh"  => "_hapi"
        fish_completion.install "completions/hapi.fish"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/hostinger/api-cli/releases/download/v1.2.0/hapi-1.2.0-linux-amd64.tar.gz"
      sha256 "30dccf99c8ea9541dfafd7274e9bd01d2325d03cacbf32413f4dca8a01acf78a"
      define_method(:install) do
        bin.install "hapi"
        bash_completion.install "completions/hapi.bash" => "hapi"
        zsh_completion.install  "completions/hapi.zsh"  => "_hapi"
        fish_completion.install "completions/hapi.fish"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/hostinger/api-cli/releases/download/v1.2.0/hapi-1.2.0-linux-arm64.tar.gz"
      sha256 "26a815ac176a414742e5c5f71ed5b66e70c0f445cd714f616095a128efd0023e"
      define_method(:install) do
        bin.install "hapi"
        bash_completion.install "completions/hapi.bash" => "hapi"
        zsh_completion.install  "completions/hapi.zsh"  => "_hapi"
        fish_completion.install "completions/hapi.fish"
      end
    end
  end
end
