# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Hostinger < Formula
  desc "Hostinger API CLI"
  homepage "https://www.hostinger.com"
  version "3.11.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/hostinger/api-cli/releases/download/v3.11.0/hostinger-3.11.0-darwin-amd64.tar.gz"
      sha256 "786b0843a6ff0dc2ffb8e430ffe3af6bf20362657296d2709761cb0c1f846aa4"

      define_method(:install) do
        bin.install "hostinger"
        bash_completion.install "completions/hostinger.bash" => "hostinger"
        zsh_completion.install  "completions/hostinger.zsh"  => "_hostinger"
        fish_completion.install "completions/hostinger.fish"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/hostinger/api-cli/releases/download/v3.11.0/hostinger-3.11.0-darwin-arm64.tar.gz"
      sha256 "2511322bd7ce082f45e1801240ae75593ebe9149b74580127db6dede38712048"

      define_method(:install) do
        bin.install "hostinger"
        bash_completion.install "completions/hostinger.bash" => "hostinger"
        zsh_completion.install  "completions/hostinger.zsh"  => "_hostinger"
        fish_completion.install "completions/hostinger.fish"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/hostinger/api-cli/releases/download/v3.11.0/hostinger-3.11.0-linux-amd64.tar.gz"
      sha256 "200158313a33c6ee7a79ae8ca7b609ba1419565d5b94df7b8d27f63ba981a81a"
      define_method(:install) do
        bin.install "hostinger"
        bash_completion.install "completions/hostinger.bash" => "hostinger"
        zsh_completion.install  "completions/hostinger.zsh"  => "_hostinger"
        fish_completion.install "completions/hostinger.fish"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/hostinger/api-cli/releases/download/v3.11.0/hostinger-3.11.0-linux-arm64.tar.gz"
      sha256 "fa7b330ae63cb0c08f60ef4f7e24a2e8dbc32f46d76a918f232d57a7e59bddcb"
      define_method(:install) do
        bin.install "hostinger"
        bash_completion.install "completions/hostinger.bash" => "hostinger"
        zsh_completion.install  "completions/hostinger.zsh"  => "_hostinger"
        fish_completion.install "completions/hostinger.fish"
      end
    end
  end
end
