# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class HostingerMail < Formula
  desc "Hostinger Mail API CLI"
  homepage "https://www.hostinger.com"
  version "1.2.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/hostinger/mail-api-cli/releases/download/v1.2.1/hostinger-mail-1.2.1-darwin-amd64.tar.gz"
      sha256 "404e138e20312337ca969c368f1c200e7143fd71688b8a626ee9b1ee0e615cbe"

      define_method(:install) do
        bin.install "hostinger-mail"
        bash_completion.install "completions/hostinger-mail.bash" => "hostinger-mail"
        zsh_completion.install  "completions/hostinger-mail.zsh"  => "_hostinger-mail"
        fish_completion.install "completions/hostinger-mail.fish"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/hostinger/mail-api-cli/releases/download/v1.2.1/hostinger-mail-1.2.1-darwin-arm64.tar.gz"
      sha256 "14c9974234f4ac3ddb92ef940c72802068fc4c99118e6443dbe63a32cc73bd6f"

      define_method(:install) do
        bin.install "hostinger-mail"
        bash_completion.install "completions/hostinger-mail.bash" => "hostinger-mail"
        zsh_completion.install  "completions/hostinger-mail.zsh"  => "_hostinger-mail"
        fish_completion.install "completions/hostinger-mail.fish"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/hostinger/mail-api-cli/releases/download/v1.2.1/hostinger-mail-1.2.1-linux-amd64.tar.gz"
      sha256 "599fbc35a9662666a049408eec6747b79898479f756a4e2e3495147017f05286"
      define_method(:install) do
        bin.install "hostinger-mail"
        bash_completion.install "completions/hostinger-mail.bash" => "hostinger-mail"
        zsh_completion.install  "completions/hostinger-mail.zsh"  => "_hostinger-mail"
        fish_completion.install "completions/hostinger-mail.fish"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/hostinger/mail-api-cli/releases/download/v1.2.1/hostinger-mail-1.2.1-linux-arm64.tar.gz"
      sha256 "16f55e3aff7a74ae02c59b732d011229a6b226c1a4be6d8ec8f3a84629acdc26"
      define_method(:install) do
        bin.install "hostinger-mail"
        bash_completion.install "completions/hostinger-mail.bash" => "hostinger-mail"
        zsh_completion.install  "completions/hostinger-mail.zsh"  => "_hostinger-mail"
        fish_completion.install "completions/hostinger-mail.fish"
      end
    end
  end
end
