# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Hostinger < Formula
  desc "Hostinger API CLI"
  homepage "https://www.hostinger.com"
  version "3.1.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/hostinger/api-cli/releases/download/v3.1.1/hostinger-3.1.1-darwin-amd64.tar.gz"
      sha256 "96cc9aee965b1f470b99b3368c7887ca0af070d0608f093a42411f3eade781d8"

      define_method(:install) do
        bin.install "hostinger"
        bash_completion.install "completions/hostinger.bash" => "hostinger"
        zsh_completion.install  "completions/hostinger.zsh"  => "_hostinger"
        fish_completion.install "completions/hostinger.fish"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/hostinger/api-cli/releases/download/v3.1.1/hostinger-3.1.1-darwin-arm64.tar.gz"
      sha256 "300af93cbfe49e259b8198c296de42b126bddf0d688b24e675b5afeb7e82a714"

      define_method(:install) do
        bin.install "hostinger"
        bash_completion.install "completions/hostinger.bash" => "hostinger"
        zsh_completion.install  "completions/hostinger.zsh"  => "_hostinger"
        fish_completion.install "completions/hostinger.fish"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/hostinger/api-cli/releases/download/v3.1.1/hostinger-3.1.1-linux-amd64.tar.gz"
      sha256 "d54fd14194455da5730677f9d913698a95b2e7f9105286d5dcc4be8b5cd24889"
      define_method(:install) do
        bin.install "hostinger"
        bash_completion.install "completions/hostinger.bash" => "hostinger"
        zsh_completion.install  "completions/hostinger.zsh"  => "_hostinger"
        fish_completion.install "completions/hostinger.fish"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/hostinger/api-cli/releases/download/v3.1.1/hostinger-3.1.1-linux-arm64.tar.gz"
      sha256 "75b734756f1e4bfb2865f00d7fe5e6482c5514c2e99747a44dde36bff4a02f51"
      define_method(:install) do
        bin.install "hostinger"
        bash_completion.install "completions/hostinger.bash" => "hostinger"
        zsh_completion.install  "completions/hostinger.zsh"  => "_hostinger"
        fish_completion.install "completions/hostinger.fish"
      end
    end
  end
end
