# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class HostingerMail < Formula
  desc "Hostinger Mail API CLI"
  homepage "https://www.hostinger.com"
  version "1.1.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/hostinger/mail-api-cli/releases/download/v1.1.2/hostinger-mail-1.1.2-darwin-amd64.tar.gz"
      sha256 "38ae6ab43e74b67d674aba6ad6aeafaaf9cbbf8ae1de1ffe4075f4aa3a6f1293"

      define_method(:install) do
        bin.install "hostinger-mail"
        bash_completion.install "completions/hostinger-mail.bash" => "hostinger-mail"
        zsh_completion.install  "completions/hostinger-mail.zsh"  => "_hostinger-mail"
        fish_completion.install "completions/hostinger-mail.fish"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/hostinger/mail-api-cli/releases/download/v1.1.2/hostinger-mail-1.1.2-darwin-arm64.tar.gz"
      sha256 "ababb09e0606f21be860f7aced27ad36455266fa13c3365b0279e8b713356873"

      define_method(:install) do
        bin.install "hostinger-mail"
        bash_completion.install "completions/hostinger-mail.bash" => "hostinger-mail"
        zsh_completion.install  "completions/hostinger-mail.zsh"  => "_hostinger-mail"
        fish_completion.install "completions/hostinger-mail.fish"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/hostinger/mail-api-cli/releases/download/v1.1.2/hostinger-mail-1.1.2-linux-amd64.tar.gz"
      sha256 "3d03107679cd19c8075f316ed56c16a9e9b2044d1b281171d74554f0829cf37e"
      define_method(:install) do
        bin.install "hostinger-mail"
        bash_completion.install "completions/hostinger-mail.bash" => "hostinger-mail"
        zsh_completion.install  "completions/hostinger-mail.zsh"  => "_hostinger-mail"
        fish_completion.install "completions/hostinger-mail.fish"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/hostinger/mail-api-cli/releases/download/v1.1.2/hostinger-mail-1.1.2-linux-arm64.tar.gz"
      sha256 "05dd5770a884e95f9225508c52ea2f0edf2964f1bd802321e9801f2b4a1a9e3f"
      define_method(:install) do
        bin.install "hostinger-mail"
        bash_completion.install "completions/hostinger-mail.bash" => "hostinger-mail"
        zsh_completion.install  "completions/hostinger-mail.zsh"  => "_hostinger-mail"
        fish_completion.install "completions/hostinger-mail.fish"
      end
    end
  end
end
