# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Hostinger < Formula
  desc "Hostinger API CLI"
  homepage "https://www.hostinger.com"
  version "3.6.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/hostinger/api-cli/releases/download/v3.6.1/hostinger-3.6.1-darwin-amd64.tar.gz"
      sha256 "70c537f7168f82dcbd73dcb1fff8948cd0f34e1dfbf002a0a2cc9f9cea1124b7"

      define_method(:install) do
        bin.install "hostinger"
        bash_completion.install "completions/hostinger.bash" => "hostinger"
        zsh_completion.install  "completions/hostinger.zsh"  => "_hostinger"
        fish_completion.install "completions/hostinger.fish"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/hostinger/api-cli/releases/download/v3.6.1/hostinger-3.6.1-darwin-arm64.tar.gz"
      sha256 "346609b92d0f72fc19faa8991e8282607be1b6811506bd89a49703af0901d058"

      define_method(:install) do
        bin.install "hostinger"
        bash_completion.install "completions/hostinger.bash" => "hostinger"
        zsh_completion.install  "completions/hostinger.zsh"  => "_hostinger"
        fish_completion.install "completions/hostinger.fish"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/hostinger/api-cli/releases/download/v3.6.1/hostinger-3.6.1-linux-amd64.tar.gz"
      sha256 "d42daa3609195bc005c15e622498ed00bf2f1e7588c61a0642384ef69578804d"
      define_method(:install) do
        bin.install "hostinger"
        bash_completion.install "completions/hostinger.bash" => "hostinger"
        zsh_completion.install  "completions/hostinger.zsh"  => "_hostinger"
        fish_completion.install "completions/hostinger.fish"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/hostinger/api-cli/releases/download/v3.6.1/hostinger-3.6.1-linux-arm64.tar.gz"
      sha256 "eb4dd6b9446ecc882a59a210deb13a51771a70e883595217f3feb65a72f5e5b0"
      define_method(:install) do
        bin.install "hostinger"
        bash_completion.install "completions/hostinger.bash" => "hostinger"
        zsh_completion.install  "completions/hostinger.zsh"  => "_hostinger"
        fish_completion.install "completions/hostinger.fish"
      end
    end
  end
end
