# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class HostingerMail < Formula
  desc "Hostinger Mail API CLI"
  homepage "https://www.hostinger.com"
  version "1.1.3"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/hostinger/mail-api-cli/releases/download/v1.1.3/hostinger-mail-1.1.3-darwin-amd64.tar.gz"
      sha256 "e052a3bd9b29e2a200a47e5f2ac6e1267de8a371a52912146b4b706654e6d67e"

      define_method(:install) do
        bin.install "hostinger-mail"
        bash_completion.install "completions/hostinger-mail.bash" => "hostinger-mail"
        zsh_completion.install  "completions/hostinger-mail.zsh"  => "_hostinger-mail"
        fish_completion.install "completions/hostinger-mail.fish"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/hostinger/mail-api-cli/releases/download/v1.1.3/hostinger-mail-1.1.3-darwin-arm64.tar.gz"
      sha256 "f4a42f0d5514bb852347d6f06358fdf6f906a7a261355007e1fbbe59d06e3a8d"

      define_method(:install) do
        bin.install "hostinger-mail"
        bash_completion.install "completions/hostinger-mail.bash" => "hostinger-mail"
        zsh_completion.install  "completions/hostinger-mail.zsh"  => "_hostinger-mail"
        fish_completion.install "completions/hostinger-mail.fish"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/hostinger/mail-api-cli/releases/download/v1.1.3/hostinger-mail-1.1.3-linux-amd64.tar.gz"
      sha256 "bdac0bcc699878610259398df386098bfc4257b003c8a82b2380dab370129fb3"
      define_method(:install) do
        bin.install "hostinger-mail"
        bash_completion.install "completions/hostinger-mail.bash" => "hostinger-mail"
        zsh_completion.install  "completions/hostinger-mail.zsh"  => "_hostinger-mail"
        fish_completion.install "completions/hostinger-mail.fish"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/hostinger/mail-api-cli/releases/download/v1.1.3/hostinger-mail-1.1.3-linux-arm64.tar.gz"
      sha256 "0d6fdda490e532c3cbec952a8ae6aff692632eb2704b4574c957591e6a3cf4aa"
      define_method(:install) do
        bin.install "hostinger-mail"
        bash_completion.install "completions/hostinger-mail.bash" => "hostinger-mail"
        zsh_completion.install  "completions/hostinger-mail.zsh"  => "_hostinger-mail"
        fish_completion.install "completions/hostinger-mail.fish"
      end
    end
  end
end
